name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies in e2e-playwright-lib
      run: |
        cd e2e-playwright-lib
        npm install

    - name: Install Playwright Browsers
      run:  |
        cd e2e-playwright-lib
        npx playwright install

    - name: Run E2E tests
      run:   |
        cd e2e-playwright-lib
        mkdir playwright-report
        npx playwright test

    - name: Generate HTML Report
      run:    |
        cd e2e-playwright-lib
        npx playwright test --output=playwright-report/
    
    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e-playwright-lib/playwright-report/
        retention-days: 30
