name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd e2e-playwright-lib
        npm install

    - name: Install Playwright Browsers
      run:  |
        cd e2e-playwright-lib
        npx playwright install

    - name: Run E2E tests
      run:   |
        cd e2e-playwright-lib
        mkdir playwright-report
        npx playwright test --reporter=html
    
    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e-playwright-lib/playwright-report/
        retention-days: 30

    - name: Upload logs in Bucket S3 AWS
      if: ${{ always() }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            echo $git_hash
            bucket=eduzze2e
            aws s3 cp ${PWD}/playwright-report/ s3://"$bucket"/"$git_hash"/ --recursive --region us-east-1
            echo "RESULT_LOG=https://eduzze2e.s3.amazonaws.com/$git_hash/log.html" >> $GITHUB_ENV

    - name: Tests ✅
      if: ${{ success() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Eduzz E2E
        message: |
            All Eduzz E2E tests passed, you're good to go!

    - name: Tests 🚨
      if: ${{ failure() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Eduzz E2E
        message: |
            There was a problem in the Eduzz E2E tests! Click here to see what went wrong:(${{ env.RESULT_LOG }})